name: datacube
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  
  # GIS and NetCDF libraries
  - xarray>=2022.3.0
  - netcdf4>=1.5.8
  - dask>=2022.2.0
  - scipy>=1.8.0
  - h5netcdf>=1.0.0
  - cartopy>=0.20.0
  - rioxarray>=0.10.0
  - rasterio>=1.3.0
  - geopandas>=0.10.0
  - cftime>=1.6.0
  
  # Testing libraries
  - pytest>=7.0.0
  - pytest-cov>=3.0.0
  
  # Development tools
  - ipykernel>=6.0.0
  - black>=22.0.0
  - flake8>=4.0.0
  
  # Optional dependencies for advanced processing
  - pip>=21.0.0
  - pip:
    - cmip6-preprocessing>=0.5.0
    - salem>=0.3.0
    - regionmask>=0.9.0
    - xesmf>=0.6.0
    - nc-time-axis>=1.4.0
    - landfire>=0.5.0